apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsdexam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fsdexam
  template:
    metadata:
      labels:
        app: fsd-business
    spec:
      containers:
      - name: fsdexam
        image: harshavardhanchowdary/fsdexam:latest
        ports:
        - containerPort: 8080
